# ==========================================
# LinkForge - Base Application Configuration
# ==========================================

# Application name
spring.application.name=LinkForge

# Active profile (switch to 'prod' for production)
spring.profiles.active=dev

# Server port
server.port=8080

# Include error messages in responses
server.error.include-message=always
server.error.include-binding-errors=always



# ==========================================
# JPA Configuration
# ==========================================

# Disable open-in-view to avoid lazy loading issues
spring.jpa.open-in-view=false



# ==========================================
# Logging
# ==========================================
logging.level.root=INFO
logging.level.com.linkforge=DEBUG



